/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CustomerOrder {
  'id' : bigint,
  'customerName' : string,
  'status' : OrderStatus,
  'orderDate' : Time,
  'trackingToken' : string,
  'totalAmount' : number,
  'advancePaid' : number,
  'balanceDue' : number,
  'items' : Array<FramingItem>,
}
export interface FramingItem {
  'size' : string,
  'thickness' : number,
  'quantity' : bigint,
  'unitPrice' : number,
}
export type OrderStatus = { 'pending' : null } |
  { 'delivered' : null } |
  { 'ready' : null };
export interface SupplierNote { 'text' : string, 'timestamp' : Time }
export type Time = bigint;
export interface _SERVICE {
  'addSupplierNote' : ActorMethod<[string], undefined>,
  'createOrder' : ActorMethod<
    [string, Array<FramingItem>, number, number, string],
    bigint
  >,
  'decrementStock' : ActorMethod<[string, bigint], undefined>,
  'deleteOrder' : ActorMethod<[bigint], undefined>,
  'getAllInventory' : ActorMethod<[], Array<[string, bigint]>>,
  'getAllOrders' : ActorMethod<[], Array<CustomerOrder>>,
  'getAllSupplierNotes' : ActorMethod<[], Array<SupplierNote>>,
  'getOrder' : ActorMethod<[bigint], CustomerOrder>,
  'getOrderByToken' : ActorMethod<[string], [] | [CustomerOrder]>,
  'getStockCount' : ActorMethod<[string], bigint>,
  'incrementStock' : ActorMethod<[string, bigint], undefined>,
  'settleBalance' : ActorMethod<[bigint, number], undefined>,
  'updateInventorySize' : ActorMethod<[string, bigint], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];