/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const FramingItem = IDL.Record({
  'size' : IDL.Text,
  'thickness' : IDL.Float64,
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Float64,
});
export const OrderStatus = IDL.Variant({
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'ready' : IDL.Null,
});
export const Time = IDL.Int;
export const CustomerOrder = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : OrderStatus,
  'orderDate' : Time,
  'trackingToken' : IDL.Text,
  'totalAmount' : IDL.Float64,
  'advancePaid' : IDL.Float64,
  'balanceDue' : IDL.Float64,
  'items' : IDL.Vec(FramingItem),
});
export const SupplierNote = IDL.Record({
  'text' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'addSupplierNote' : IDL.Func([IDL.Text], [], []),
  'createOrder' : IDL.Func(
      [IDL.Text, IDL.Vec(FramingItem), IDL.Float64, IDL.Float64, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'decrementStock' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'deleteOrder' : IDL.Func([IDL.Nat], [], []),
  'getAllInventory' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getAllOrders' : IDL.Func([], [IDL.Vec(CustomerOrder)], ['query']),
  'getAllSupplierNotes' : IDL.Func([], [IDL.Vec(SupplierNote)], ['query']),
  'getOrder' : IDL.Func([IDL.Nat], [CustomerOrder], ['query']),
  'getOrderByToken' : IDL.Func([IDL.Text], [IDL.Opt(CustomerOrder)], ['query']),
  'getStockCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'incrementStock' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'settleBalance' : IDL.Func([IDL.Nat, IDL.Float64], [], []),
  'updateInventorySize' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const FramingItem = IDL.Record({
    'size' : IDL.Text,
    'thickness' : IDL.Float64,
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Float64,
  });
  const OrderStatus = IDL.Variant({
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'ready' : IDL.Null,
  });
  const Time = IDL.Int;
  const CustomerOrder = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : OrderStatus,
    'orderDate' : Time,
    'trackingToken' : IDL.Text,
    'totalAmount' : IDL.Float64,
    'advancePaid' : IDL.Float64,
    'balanceDue' : IDL.Float64,
    'items' : IDL.Vec(FramingItem),
  });
  const SupplierNote = IDL.Record({ 'text' : IDL.Text, 'timestamp' : Time });
  
  return IDL.Service({
    'addSupplierNote' : IDL.Func([IDL.Text], [], []),
    'createOrder' : IDL.Func(
        [IDL.Text, IDL.Vec(FramingItem), IDL.Float64, IDL.Float64, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'decrementStock' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'deleteOrder' : IDL.Func([IDL.Nat], [], []),
    'getAllInventory' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getAllOrders' : IDL.Func([], [IDL.Vec(CustomerOrder)], ['query']),
    'getAllSupplierNotes' : IDL.Func([], [IDL.Vec(SupplierNote)], ['query']),
    'getOrder' : IDL.Func([IDL.Nat], [CustomerOrder], ['query']),
    'getOrderByToken' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(CustomerOrder)],
        ['query'],
      ),
    'getStockCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'incrementStock' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'settleBalance' : IDL.Func([IDL.Nat, IDL.Float64], [], []),
    'updateInventorySize' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };